Add envs
lambdazy/lzy pull request #820
Opened 2023-02-14 08:53 UTC by ArtoLord

2023-02-14 10:10 UTC, imakunin commented on lzy-api/src/main/proto/ai/lzy/v1/workflow/workflow.proto
> +  /* optional */ map<string, string> envVariables = 9;  // Environment variables to run operation with
let's rename to to `env`

2023-02-14 10:15 UTC, imakunin commented on model/src/main/proto/ai/lzy/v1/common/env.proto
> +  BaseEnv baseEnv = 1 [deprecated=true];  // TODO(artolord) remove after next minor
remove it right now

2023-02-14 10:15 UTC, imakunin commented on model/src/main/proto/ai/lzy/v1/common/env.proto
> +  /* optional */ map<string, string> envVariables = 4;
just `env`

2023-02-14 10:15 UTC, imakunin commented on model/src/main/proto/ai/lzy/v1/common/env.proto
> +  oneof env {
not `env` but `runtimeSpec`

2023-02-14 10:15 UTC, imakunin commented on model/src/main/proto/ai/lzy/v1/common/env.proto
> +    PythonEnv pyenv = 5;
`PythonRuntimeSpec`

2023-02-14 10:15 UTC, imakunin commented on model/src/main/proto/ai/lzy/v1/common/env.proto
> +    ProcessEnv process_env = 6;
`BashRuntimeSpec`

2023-02-14 21:32 UTC, mrMakaronka requested changes
No python unit tests on setting/merging env variables in workflow/op. Please add them to `LzyOpParamsTests`

2023-02-15 08:06 UTC, ArtoLord commented
> No python unit tests on setting/merging env variables in workflow/op. Please add them to `LzyOpParamsTests`

Fixed

2023-02-15 09:05 UTC, imakunin commented on lzy-api/src/main/proto/ai/lzy/v1/workflow/workflow.proto
> +  message PythonEnvSpec {
maybe we should rename it to `PythonRunnerSpec` and rename `env` on line 22 to `runner`

2023-02-15 09:11 UTC, imakunin commented on model/src/main/proto/ai/lzy/v1/common/env.proto
> +  oneof env {
or `runner`

2023-02-15 12:53 UTC, imakunin approved these changes

2023-02-15 13:18 UTC, merged